server {
    listen 80;
    server_name dialogochat.ru www.dialogochat.ru;
    client_max_body_size 50M;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dialogochat.ru www.dialogochat.ru;

    client_max_body_size 50M;

    # Пути должны быть именно такими, так как мы пробросили папку certs в /etc/nginx/ssl
    ssl_certificate /etc/nginx/ssl/certificate.crt;
    ssl_certificate_key /etc/nginx/ssl/certificate.key;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://messenger_backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /uploads/ {
        proxy_pass http://messenger_backend:8080;
        proxy_set_header Host $host;
    }

    location /ws {
        proxy_pass http://messenger_backend:8080/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # КРИТИЧЕСКИ ВАЖНО: Увеличиваем таймаут
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
