services:
  postgres:
    image: postgres:16-alpine
    container_name: messenger_db
    restart: always
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
      POSTGRES_DB: chat_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat_user -d chat_database"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: messenger_backend
    restart: always
    environment:
      DB_URL: "postgres://chat_user:chat_password@postgres:5432/chat_database?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"